before_script:
  - pip install -U https://github.com/python-adaptive/adaptive/archive/master.zip
  - conda install -y sympy==1.1

notes:
  script:
    - cd progress_report
    - pdflatex progress.tex
    - pdflatex progress.tex

  artifacts:
    paths:
    - progress_report/*.pdf


paper:
  script:
    - cd paper
    - mkdir -p figures
    - make plot pdf
  artifacts:
    paths:
      - paper/snakemajoranas.pdf
