paper:
  script:
    - pip install 'fsspec>=0.3.3'
    - cd paper
    - mkdir -p figures
    - make plot pdf referee_responses
  artifacts:
    paths:
      - paper/zigzag.pdf
      - paper/figures/*pdf
      - paper/referee_responses.pdf
      - paper/referee_responses_round_2.pdf
      - paper/appendix.pdf
