report:
	pdflatex report.tex
introduction: introduction.tex
	pdflatex "\includeonly{introduction.tex}\input{report.tex}"
preface: preface.tex
	pdflatex "\includeonly{preface.tex}\input{report.tex}"
discussion: discussion.tex
	pdflatex "\includeonly{discussion.tex}\input{report.tex}"
methods: methods.tex
	pdflatex "\includeonly{methods.tex}\input{report.tex}"
theory: theory.tex
	pdflatex "\includeonly{theory.tex}\input{report.tex}"
title: title.tex
	pdflatex "\includeonly{title.tex}\input{report.tex}"
